### PR TITLE
The deprecated calling sytle of circut draw function has been updated in tutorials.

### PR DESCRIPTION
**Pull request by espREssOOOHHH**
Dear Maintainers,

I hope this message finds you well. I've noticed a small issue within the neural networks tutorial (docs/tutorials/01_neural_networks.ipynb), specifically in code block #26. It appears that the line qc1.draw(\"mpl\") is incompatible with qiskit version 0.45.2.

I've taken the liberty of updating the code to ensure compatibility with the specified version of qiskit. I believe this adjustment will enhance the tutorial's reliability for users working with the current version.

Thank you for considering this fix. I look forward to your feedback.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
Hi, you fixed one of the places in the file, not the other (this is what the output from CI looks like now at this place in the file)

image

I would suggest you restart/re-run the entire tutorial after making changes - call 26 confused me until I see this is how it is numbered since it did not start at 1.

This is just one of a number of tutorials that need updating for which I raised #725 a while back. I fixed one in the list when I needed to update it as part of another fix but the others all still need doing.

**Comment by woodsp-ibm** [comment]
Thanks for the updates in the rest of the tutorials too. There is one place that it seems you missed in `12_quantum_autoencoder.ipynb` I noticed it in the build output from CI here but you can see it in the notebook on your fork too

image

**Comment by espREssOOOHHH** [comment]
Dear @woodsp-ibm ,

Thank you for pointing out the missed update in the "12_quantum_autoencoder.ipynb" tutorial. I have reviewed the notebook and located the section you mentioned. I'm happy to inform you that I've now fixed this and updated the calling style of the circuit draw function in this part of the tutorial as well.

**Review by woodsp-ibm — APPROVED** [review]
Thanks for contribution which takes care of the deprecation warnings, due to the former usage of circuit draw() in the notebooks.

**Pull request merged**
