### PR TITLE
Improved content for Tutorial 2 (QAMP fall'22) 

### PR DESCRIPTION
**Pull request by SanyaNanda**
### Summary
Enhancing the documentation of Tutorial "02_classifier_regressor" as a mentee for QAMP 2022.
Mentor: @ElePT
Mentee: @SanyaNanda

### Details and comments
Restructured the notebook (Objective, Introduction, Tutorial and what was learned)
Imports placed where required
Added Detailed Explanations in all the sections
Inline comments for better understanding of the code and arguments used in function
Hyperlinks to API references wherever required

### CODE REVIEW

**Comment by SanyaNanda** [comment]
As of now, I have completed the classification section

These are some of my queries:
1. I am getting an error in cell 10 and 19 saying: AttributeError: 'NeuralNetworkClassifier' object has no attribute 'weights'
2. I am getting error in cell 28 saying: QiskitMachineLearningError: "Shapes don't match, predict: (10, 10), target: (10, 3)!" 
3. While adding explanations in some areas I couldn't understand the code, like
3.1. Relevance of cell 6
3.2. What is objective function in callback_graph?
3.3. Is callback_function same as epoch and the declining value is the reducing error?
4. Should I add inline comments in cell 14 explaining the parameters? They have already been explained in tutorial 1
5. Should I add inline comments in cell 15 explaining the parameters? It has been explained in cell 5 already

Apart from these points, classification section of the tutorial is done and is ready for review.

**Comment by SanyaNanda** [comment]
I have improved the regression section as well, with this the tutorial is ready for review

**Comment by SanyaNanda** [comment]
Also I removed the following imports as they were not being used anywhere in the code

from qiskit.opflow import Z, I, StateFn
from typing import Union
from qiskit_machine_learning.exceptions import QiskitMachineLearningError

**Comment by woodsp-ibm** [comment]
I don't believe you made any changes to the other file `02a_training_a_quantum_model_on_a_real_dataset.ipynb` which is part of this PR. It looks like you might have run/saved it locally where your environment removed the ids in the cells. Hence it shows a bunch of changes, but I think its all down to ids being removed. If there are no local changes you explicitly did I suggest reverting this notebook back so this PR just has the updated 02 classifier regressor one.

**Comment by SanyaNanda** [comment]
In 2a, I have added the following
1. Further exploratory links to APIs used
2. Summary of steps followed in important sections

As a first time reader, I found 2a interesting and already complete in itself

**Comment by adekusar-drl** [comment]
Thanks for taking care of this. The 02 and 02a tutorials were slightly changed. Could you please merge your work with the latest version of the tutorial? I can help if you have issues.

**Comment by SanyaNanda** [comment]
Thank you! I will do this and get in touch in case of queries

Also the issue in the environment is resolved and I am able to run all cells

**Comment by oscar-wallis** [comment]
Hi @SanyaNanda, we at the Hartree Centre recently became developers of the qiskit-machine-learning library, we are interested in updating the qml tutorials, but as these PRs were made some time ago, they seem to now be using deprecated syntax. Would you be interested in helping to update these?

**Comment by oscar-wallis** [comment]
### Action Taken
I have made a [new repo](https://github.com/oscar-wallis/qml-tutorial-update) forked from @SanyaNanda's [tutorial repo](https://github.com/SanyaNanda/qiskit-machine-learning) and updated it to Qiskit machine learning 0.7.2. I will work to try and update these tutorials and if @SanyaNanda is interested she is welcome to help. In the mean time, I will close this and associated PRs.

**Pull request closed without merging**
